services:
  test-postgres:
    image: postgres:latest
    container_name: l0-test-postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_orders_db
    ports:
      - "5433:5432"  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-redis:
    image: redis:latest
    container_name: l0-test-redis
    ports:
      - "6380:6379"  
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
